#!/bin/bash
################################################################################
# Zelogx™ Multi-Project Secure Lab Setup
#
# © 2025 Zelogx. Zelogx™ and the Zelogx logo are trademarks
# of the Zelogx Project. All other marks are property of their respective owners.
#
# Filename: 0102_setupNetwork.sh
# Purpose: Create Proxmox SDN (zones, vnets, subnets), IPSets, datacenter
#          firewall rules and gateway hooks for MSL Setup
#
# Main functions/commands used:
#   - pvesh: Proxmox API operations
#   - jq: JSON processing
#   - lib/sdn_backup_restore.sh: Backup / restore to the pre-MSL state
#
# Dependencies:
#   - pvesh, jq, bash
#
# Usage:
#   ./0102_setupNetwork.sh [en|jp]            # Normal run (backup or restore, then recreate)
#   ./0102_setupNetwork.sh [en|jp] --restore  # Restore only (delete and exit)
#   Normally called from 01_networkSetup.sh / 99_uninstall.sh.
#
# Notes:
#   - Requires .env generated by 00_configNetwork.sh
#   - First run backs up the pre-MSL state; re-runs restore to that state
#     and recreate everything (not a differential update)
#   - Refuses to run standalone while MSL cluster mode is enabled
################################################################################


set -euo pipefail

print_usage() {
        # Always show English usage (spec v2.0)
        cat <<'USAGE'
Usage: 0102_setupNetwork.sh [en|jp] [--restore]
    en|jp       : Console language (default: en)
    --restore   : Restore SDN/firewall to backup state and exit
Notes:
    - Requires .env file with network variables
    - First run creates backup; subsequent runs are idempotent
USAGE
}

MSL_LANG=""
RESTORE_ONLY=false
LANG_SET=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        en|jp)
            if [[ "$LANG_SET" == true ]]; then
                echo "[ERROR] Multiple language codes specified"
                print_usage
                exit 1
            fi
            MSL_LANG="$1"
            LANG_SET=true
            shift ;;
        --restore)
            RESTORE_ONLY=true ; shift ;;
        -h|--help)
            print_usage; exit 0 ;;
        *)
            echo "[ERROR] Unknown argument: $1"
            print_usage
            exit 1 ;;
    esac
done

# Default to English if no language specified
if [[ -z "$MSL_LANG" ]]; then
    MSL_LANG="en"
fi
export MSL_LANG

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_ROOT"

# Common library (logging, etc.)
# shellcheck source=/dev/null
source "$SCRIPT_ROOT/lib/common.sh"

 # RESTORE_ONLY already set in arg loop

# Multi-language messages (console output)
if [[ "${MSL_LANG}" == "en" ]]; then
    # shellcheck source=/dev/null
    source "$SCRIPT_ROOT/lib/messages_en.sh"
else
    # shellcheck source=/dev/null
    source "$SCRIPT_ROOT/lib/messages_jp.sh"
fi

# Router prompt functions
# shellcheck source=/dev/null
source "$SCRIPT_ROOT/lib/router_prompt.sh"

# Load .env
env_file=".env"
if [[ ! -f "$env_file" ]]; then
    echo "[ERROR] $MSG_SDN_ENV_MISSING"
    exit 1
fi
source "$env_file"

# In cluster mode, zones/IPSets/rules are shared with mslcm (vxlan_peers, zone
# peers, keepalived hooks). Running 0102 alone would restore them away and leave
# the cluster half-configured, so require the orchestrator, which runs
# 0103 --restore (removing /etc/pve/mslsetup) before calling 0102.
if [[ -f /etc/pve/mslsetup/cluster.env ]]; then
    log_error "Cluster mode is enabled (/etc/pve/mslsetup/cluster.env exists); refusing to run 0102 standalone"
    echo "[ERROR] $MSG_SDN_CLUSTER_MODE_ENABLED"
    exit 1
fi

################################################################################
# Function: remove_msl_dc_access_rules
# Description: Remove all MSL datacenter access rules (Spice/ssh/https) by
#              comment pattern
#
# Main commands/functions used:
#   - msl_delete_dc_rules_matching: Delete rules whose comment matches ERE
################################################################################
remove_msl_dc_access_rules() {
    msl_delete_dc_rules_matching "$MSL_DC_ACCESS_RULE_COMMENT_REGEX" \
        || log_warn "Failed to delete some datacenter access rules"
}

################################################################################
# Function: check_reserved_names_unused
# Description: Exit if any SDN zone / VNet / IPSet name reserved for MSL Setup
#              already exists (checked on the first install only). Existing
#              objects with these names are never reused.
#
# Main commands/functions used:
#   - pvesh get / jq: List zones, VNets and IPSets
################################################################################
check_reserved_names_unused() {
    local zones vnets ipsets name
    local in_use=()
    zones=$(pvesh get /cluster/sdn/zones --output-format json | jq -r '.[].zone') \
        || die "Failed to list SDN zones. See log: ${LOG_FILE}"
    vnets=$(pvesh get /cluster/sdn/vnets --output-format json | jq -r '.[].vnet') \
        || die "Failed to list SDN VNets. See log: ${LOG_FILE}"
    ipsets=$(pvesh get /cluster/firewall/ipset --output-format json | jq -r '.[].name') \
        || die "Failed to list firewall IPSets. See log: ${LOG_FILE}"

    while IFS= read -r name; do
        [[ "$name" =~ ^(vpndmz|devpj[0-9]{2})$ ]] && in_use+=("zone:${name}")
    done <<< "$zones"
    while IFS= read -r name; do
        [[ "$name" =~ ^(vpndmzvn|vnetpj[0-9]{2})$ ]] && in_use+=("vnet:${name}")
    done <<< "$vnets"
    while IFS= read -r name; do
        [[ "$name" =~ ^(devpjs|mainlan|vpn_guest_pool|all_private_ip|vxlan_peers)$ ]] && in_use+=("ipset:${name}")
    done <<< "$ipsets"

    if (( ${#in_use[@]} > 0 )); then
        log_error "Reserved names already in use: ${in_use[*]}"
        rmdir "$backup_dir" 2>/dev/null || true
        printf "[ERROR] ${MSG_SDN_RESERVED_NAMES_IN_USE}\n" "${in_use[*]}"
        exit 1
    fi
    log_info "Reserved names check passed (no zone/vnet/IPSet name conflicts)"
}

################################################################################
# Function: remove_msldhcp_artifacts
# Description: Remove /usr/local/bin/msldhcp (installed by this script) and the
#              host-side DHCP export created by msldhcp (path/service units,
#              exporter script, /var/lib/mslsetup/dhcp). DHCP CTs themselves
#              must be deleted by the user before uninstalling.
#
# Main commands/functions used:
#   - systemctl: Stop/disable the export path unit
#   - rm: Delete files
################################################################################
remove_msldhcp_artifacts() {
    local unit
    if [[ -f /etc/systemd/system/msl-dhcp-export-all.path || -f /etc/systemd/system/msl-dhcp-export-all.service ]]; then
        systemctl disable --now msl-dhcp-export-all.path >/dev/null 2>&1 || true
        for unit in msl-dhcp-export-all.path msl-dhcp-export-all.service; do
            rm -f "/etc/systemd/system/${unit}"
        done
        systemctl daemon-reload >/dev/null 2>&1 || true
        log_info "Removed msldhcp host units (msl-dhcp-export-all.path/.service)"
    fi
    rm -f /usr/local/sbin/msl-dhcp-export-all
    rm -rf /var/lib/mslsetup/dhcp
    rmdir /var/lib/mslsetup 2>/dev/null || true
    rm -f /usr/local/bin/msldhcp
    log_info "Removed msldhcp command and DHCP export state (if present)"
}

################################################################################
# Function: remove_msl_project_inet_drop_rules
# Description: Remove all per-project internet egress DROP rules by comment
#              pattern (independent of current NUM_PJ)
#
# Main commands/functions used:
#   - msl_delete_dc_rules_matching: Delete rules whose comment matches ERE
################################################################################
remove_msl_project_inet_drop_rules() {
    msl_delete_dc_rules_matching "$MSL_INET_DROP_RULE_COMMENT_REGEX" \
        || log_warn "Failed to delete some internet DROP rules"
}

################################################################################
# SDN backup / restore (implemented in lib/sdn_backup_restore.sh)
################################################################################
backup_dir="sdn_backup"
mkdir -p "$backup_dir"
backup_complete_flag="$backup_dir/.backup_complete"
had_backup=false
if [[ -f "$backup_complete_flag" ]]; then
    had_backup=true
fi

# shellcheck source=/dev/null
source "$SCRIPT_ROOT/lib/sdn_backup_restore.sh"

# Backup/restore flow (v2.0):
# 1. If --restore specified: restore to backup state, then delete the backup
#    (and msldhcp) and exit. The next normal run takes a fresh backup, so a
#    stale backup is never applied after an uninstall / reinstall.
# 2. Normal run without backup: back up the pre-MSL state FIRST
# 3. Normal run with backup: restore first, then provision
if [[ "$RESTORE_ONLY" == true ]]; then
    if [[ "$had_backup" == true ]]; then
        log_info "Restore flag detected; performing restore and exiting"
        clear_project_vnet_dhcp_ranges
        msl_restore_to_backup
        remove_project_gateway_hooks
        echo "[SUCCESS] $MSG_SDN_RESTORE_ONLY_DONE"
    else
        log_warn "Restore flag detected, but no backup existed at start; skipping restore"
        clear_project_vnet_dhcp_ranges
        remove_msl_dc_access_rules
        remove_msl_project_inet_drop_rules
        remove_project_gateway_hooks
        echo "[SUCCESS] $MSG_SDN_RESTORE_NO_BACKUP"
    fi
    remove_msldhcp_artifacts
    rm -rf "${backup_dir:?}"
    log_info "Removed SDN backup directory: ${backup_dir}"
    exit 0
fi

if [[ "$had_backup" == false ]]; then
    # First install: refuse if reserved names are already in use, before the
    # backup is taken (a backup containing them would make later restores keep
    # MSL's own objects of the same name).
    check_reserved_names_unused
    log_info "No backup found. Creating initial state backup before provisioning..."
    msl_perform_backup
fi

# Normal run: only restore if backup existed at start
if [[ "$had_backup" == true ]]; then
    log_info "Backup existed at start. Restoring to initial state before provisioning..."
    clear_project_vnet_dhcp_ranges
    msl_restore_to_backup
else
    log_info "First run (no prior backup). Skipping restore before provisioning."
fi

################################################################################
# Create SDN zones
################################################################################
echo -n "$MSG_SDN_CREATING_ZONES"
zone_peer_ip="$PVE_IP"
log_info "Creating vpndmz as VXLAN with self peer: ${zone_peer_ip}"
log_info "Creating devpj zones as VXLAN with self peer: ${zone_peer_ip}"
log_info "MTU policy: use Proxmox default (AUTO) when available"
create_sdn_zone "vpndmz" "vxlan" "--ipam pve --peers ${zone_peer_ip}"
for i in $(seq 1 "$NUM_PJ"); do
    idx=$(printf '%02d' "$i")
    create_sdn_zone "devpj${idx}" "vxlan" "--ipam pve --peers ${zone_peer_ip}"
done
echo " [OK]"

################################################################################
# Create SDN VNets
################################################################################
echo -n "$MSG_SDN_CREATING_VNETS"
create_sdn_vnet "vpndmzvn" "vpndmz" "-tag 10000"
for i in $(seq 1 "$NUM_PJ"); do
    idx=$(printf '%02d' "$i")
    vnet_tag="100${idx}"
    create_sdn_vnet "vnetpj${idx}" "devpj${idx}" "-tag ${vnet_tag}"
done
echo " [OK]"

################################################################################
# Create SDN subnets
################################################################################
echo -n "$MSG_SDN_CREATING_SUBNETS"
create_sdn_subnet "$VPNDMZ_CIDR" "vpndmzvn" "-gateway $VPNDMZ_GW"
for i in $(seq 1 "$NUM_PJ"); do
    idx=$(printf '%02d' "$i")
    cidr_var="PJ${idx}_CIDR"
    gw_var="PJ${idx}_GW"
    create_sdn_subnet "${!cidr_var}" "vnetpj${idx}" "-gateway ${!gw_var}"
    set_vnet_subnet_dhcp_range "vnetpj${idx}" "${!cidr_var}" \
        || die "Failed to set DHCP range on vnetpj${idx}. See log: ${LOG_FILE}"
done
echo " [OK]"

################################################################################
# SDN Apply
################################################################################
echo -n "$MSG_SDN_APPLY_START"
log_info "$MSG_SDN_APPLY_START"
pvesh_logged "apply SDN configuration" set /cluster/sdn \
    || die "SDN apply failed. See log: ${LOG_FILE}"
log_info "SDN configuration applied successfully"
echo " [OK]"

################################################################################
# Create IPSets
################################################################################
log_info "$MSG_SDN_IPSET_START"
echo "$MSG_SDN_IPSET_START"

# IPSet: devpjs (All development project networks)
log_info "Creating IPSet devpjs..."
# Create IPSet for devpjs
create_ipset "devpjs" "All development project networks"
# Adding entries for each project network
for i in $(seq 1 "$NUM_PJ"); do
    idx=$(printf '%02d' "$i")
    cidr_var="PJ${idx}_CIDR"
    cidr="${!cidr_var}"
    create_ipset_entry "devpjs" "${cidr}" "Project ${idx} network"
done
log_info "  IPSet devpjs created with $NUM_PJ entries"
echo " [OK]"

# IPSet: mainlan (MainLAN)
# Create IPSet mainlan
create_ipset "mainlan" "Main LAN network"
# Add CIDR entries to IPSets
create_ipset_entry "mainlan" "$ML_CIDR" "MainLAN"
log_info "  IPSet mainlan completed"
echo " [OK]"

# IPSet: vpn_guest_pool (VPN Client Pool)
log_info "Creating IPSet vpn_guest_pool..."
create_ipset "vpn_guest_pool" "VPN client IP pool"
create_ipset_entry "vpn_guest_pool" "$VPN_POOL" "VPN client pool"
echo " [OK]"

# IPSet: all_private_ip (All private IP ranges) - v2.0 added
create_ipset "all_private_ip" "All private IP address ranges (RFC1918 + loopback)"
create_ipset_entry "all_private_ip" "10.0.0.0/8" "Class A private"
create_ipset_entry "all_private_ip" "172.16.0.0/12" "Class B private"
create_ipset_entry "all_private_ip" "192.168.0.0/16" "Class C private"
create_ipset_entry "all_private_ip" "127.0.0.0/8" "Loopback"
echo " [OK]"
log_info "  IPSet all_private_ip completed with 4 entries"

################################################################################
# Datacenter firewall options (v2.0: enable host firewall + nftables)
################################################################################
dc_fw_enable_initial=$(pvesh get /cluster/firewall/options --output-format json 2>/dev/null | jq -r '.enable // 0' || echo "0")
dc_fw_was_off=false
if [[ "$dc_fw_enable_initial" != "1" ]]; then
    dc_fw_was_off=true
fi

log_info "$MSG_SDN_FW_OPTIONS"
log_info "Datacenter firewall initial enable state: ${dc_fw_enable_initial}"
# Tenant isolation depends on both datacenter and host firewall being enabled.
# Stop here on failure: after fixing the cause, re-running restores and retries.
echo -n "Setting datacenter firewall options..."
if ! pvesh_logged "enable datacenter firewall" set /cluster/firewall/options -enable 1; then
    echo " [ERROR]"
    echo "[ERROR] $MSG_SDN_FW_OPTIONS_ERROR"
    die "Failed to enable datacenter firewall; tenant isolation would not be enforced. See log: ${LOG_FILE}"
fi
echo " [OK]"

# Enable host firewall and nftables (v2.0 added)
node_name=$(hostname)
log_info "Enabling host firewall and nftables on node $node_name..." -c
if ! pvesh_logged "enable host firewall/nftables on ${node_name}" set "/nodes/${node_name}/firewall/options" -enable 1 -nftables 1; then
    echo "Host firewall/nftables........... [ERROR]"
    die "Failed to enable host firewall/nftables on ${node_name}; tenant isolation would not be enforced. See log: ${LOG_FILE}"
fi
log_info "  Host firewall and nftables enabled successfully" -c
echo "Host firewall/nftables........... [OK]"

################################################################################
# Datacenter-level Firewall Rules (v2.0: replaces Security Group pj-dev)
################################################################################
log_info "Creating datacenter-level FW rules..."
echo -n "Creating datacenter-level FW rules"

if [[ "$dc_fw_was_off" == true ]]; then
    log_info "  Datacenter firewall was OFF at start; adding DC access rules"
    log_info "  Access rule: IN ACCEPT +dc/all_private_ip → tcp/3128"
    pvesh_logged "create DC rule (Spice access)" create "/cluster/firewall/rules" \
        -pos 0 -action ACCEPT -type in -source "+dc/all_private_ip" -proto tcp -dport 3128 -enable 1 \
        -comment "MSLSetup Allow Spice from external network to DC" \
        || die "Failed to create datacenter firewall rule (Spice access). See log: ${LOG_FILE}"
    log_info "  Access rule: IN ACCEPT +dc/all_private_ip → tcp/22"
    pvesh_logged "create DC rule (ssh access)" create "/cluster/firewall/rules" \
        -pos 0 -action ACCEPT -type in -source "+dc/all_private_ip" -proto tcp -dport 22 -enable 1 \
        -comment "MSLSetup Allow ssh from external network to DC" \
        || die "Failed to create datacenter firewall rule (ssh access). See log: ${LOG_FILE}"
    log_info "  Access rule: IN ACCEPT +dc/all_private_ip → tcp/8006"
    pvesh_logged "create DC rule (https access)" create "/cluster/firewall/rules" \
        -pos 0 -action ACCEPT -type in -source "+dc/all_private_ip" -proto tcp -dport 8006 -enable 1 \
        -comment "MSLSetup Allow https from external network to DC" \
        || die "Failed to create datacenter firewall rule (https access). See log: ${LOG_FILE}"
    echo -n "."
else
    log_info "  Datacenter firewall was already ON at start; skipping DC access rules"
fi

# Base DROP rule (always)
# Per-project internet egress DROP rules (added before private-range DROP)
for i in $(seq "$NUM_PJ" -1 1); do
    idx=$(printf '%02d' "$i")
    log_info "  DROP rule: FORWARD DROP +sdn/vnetpj${idx}-all → any"
    pvesh_logged "create DC rule (internet DROP PJ${idx})" create "/cluster/firewall/rules" \
        -action DROP -type forward -source "+sdn/vnetpj${idx}-all" -enable 0 \
        -comment "MSLSetup Disallow internet access for PJ${idx}" || log_warn "Failed to add internet DROP rule for PJ${idx}"
    echo -n "."
done

log_info "  DROP rule: FORWARD DROP +dc/devpjs → +dc/all_private_ip"
pvesh_logged "create DC rule (devpjs private DROP)" create "/cluster/firewall/rules" \
    -action DROP -type forward -source "+dc/devpjs" -dest "+dc/all_private_ip" -enable 1 \
    -comment "MSLSetup Drop devpjs to all private networks" \
    || die "Failed to create datacenter firewall rule (devpjs private DROP). See log: ${LOG_FILE}"
echo -n "."
# DNS_IP1 (only if private)
if validate_private_ip "${DNS_IP1:-}"; then
    log_info "  DNS rule: FORWARD ACCEPT +dc/devpjs → $DNS_IP1:53/udp"
    pvesh_logged "create DC rule (DNS UDP to ${DNS_IP1})" create "/cluster/firewall/rules" \
        -action ACCEPT -type forward -source "+dc/devpjs" -dest "$DNS_IP1" -dport 53 -proto udp -enable 1 \
        -comment "MSLSetup Allow DNS UDP to $DNS_IP1" \
        || die "Failed to create datacenter firewall rule (DNS UDP to ${DNS_IP1}). See log: ${LOG_FILE}"
    log_info "  DNS rule: FORWARD ACCEPT +dc/devpjs → $DNS_IP1:53/tcp"
    pvesh_logged "create DC rule (DNS TCP to ${DNS_IP1})" create "/cluster/firewall/rules" \
        -action ACCEPT -type forward -source "+dc/devpjs" -dest "$DNS_IP1" -dport 53 -proto tcp -enable 1 \
        -comment "MSLSetup Allow DNS TCP to $DNS_IP1" \
        || die "Failed to create datacenter firewall rule (DNS TCP to ${DNS_IP1}). See log: ${LOG_FILE}"
else
    log_info "  Skipping DNS_IP1 ($DNS_IP1) - not private"
fi
echo -n "."
# DNS_IP2 (only if defined and private)
if [[ -n "${DNS_IP2:-}" ]]; then
    if validate_private_ip "$DNS_IP2"; then
        log_info "  DNS rule: FORWARD ACCEPT +dc/devpjs → $DNS_IP2:53/udp"
        pvesh_logged "create DC rule (DNS UDP to ${DNS_IP2})" create "/cluster/firewall/rules" \
            -action ACCEPT -type forward -source "+dc/devpjs" -dest "$DNS_IP2" -dport 53 -proto udp -enable 1 \
            -comment "MSLSetup Allow DNS UDP to $DNS_IP2" || log_warn "Failed to add DNS_IP2 UDP rule"
        log_info "  DNS rule: FORWARD ACCEPT +dc/devpjs → $DNS_IP2:53/tcp"
        pvesh_logged "create DC rule (DNS TCP to ${DNS_IP2})" create "/cluster/firewall/rules" \
            -action ACCEPT -type forward -source "+dc/devpjs" -dest "$DNS_IP2" -dport 53 -proto tcp -enable 1 \
            -comment "MSLSetup Allow DNS TCP to $DNS_IP2" || log_warn "Failed to add DNS_IP2 TCP rule"
    else
        log_info "  Skipping DNS_IP2 ($DNS_IP2) - not private"
    fi
fi
echo -n "."
# Intra-VNet communication rules (one per project)
for i in $(seq "$NUM_PJ" -1 1); do
    idx=$(printf '%02d' "$i")
    log_info "  Intra-VNet rule: FORWARD ACCEPT +sdn/vnetpj${idx}-all → +sdn/vnetpj${idx}-all"
    pvesh_logged "create DC rule (intra-vnet PJ${idx})" create "/cluster/firewall/rules" \
        -action ACCEPT -type forward -source "+sdn/vnetpj${idx}-all" -dest "+sdn/vnetpj${idx}-all" -enable 1 \
        -comment "MSLSetup Allow intra-vnet PJ${idx}" || log_warn "Failed to add vnetpj${idx} east-west rule"
    echo -n "."
done

# Allow icmp to gateways (created disabled; Phase 2 will enable just for validation)
icmp_rule1_comment="MSLSetup ICMP Prtn VPNDMZ GW"
icmp_rule2_comment="MSLSetup ICMP Prtn DEVPJS"
icmp_rule3_comment="MSLSetup ICMP Prtn MAINLAN ANY"

log_info "  ICMP rule1: in ACCEPT +sdn/vpndmzvn-no-gateway → +sdn/vpndmzvn-gateway"
pvesh_logged "create DC rule (ICMP rule1)" create "/cluster/firewall/rules" \
    -action ACCEPT -type in -source "+sdn/vpndmzvn-no-gateway" -dest "+sdn/vpndmzvn-gateway" -proto icmp -enable 0 \
    -comment "$icmp_rule1_comment" || log_warn "Failed to add icmp rule1"
echo -n "."
log_info "  ICMP rule2: in ACCEPT +sdn/vpndmzvn-no-gateway → +dc/devpjs"
pvesh_logged "create DC rule (ICMP rule2)" create "/cluster/firewall/rules" \
    -action ACCEPT -type in -source "+sdn/vpndmzvn-no-gateway" -dest "+dc/devpjs" -proto icmp -enable 0 \
    -comment "$icmp_rule2_comment" || log_warn "Failed to add icmp rule2"
echo -n "."
log_info "  ICMP rule3: in ACCEPT +dc/mainlan → any"
pvesh_logged "create DC rule (ICMP rule3)" create "/cluster/firewall/rules" \
    -action ACCEPT -type in -source "+dc/mainlan" -proto icmp -enable 0 \
    -comment "$icmp_rule3_comment" || log_warn "Failed to add icmp rule3"
echo -n "."

# Keep ICMP rule comments as fixed identifiers in scripts (not persisted to .env)
echo " [OK]"
log_info "  Datacenter-level FORWARD/IN rules completed."

################################################################################
# Gateway hooks: GW IPs on vpndmzvn / vnetpjXX and the return route
# (VPN_POOL via PT_EG_IP) are applied by the if-up.d/if-down.d hooks.
# Interface existence is not checked or monitored here (by design).
################################################################################
persist_project_gateway_hooks
echo "Adding PJ gateway hooks.......... [OK]"
log_info "$MSG_SDN_DONE"

################################################################################
# FINAL STATE DUMP (complete details)
################################################################################
log_info "==== FINAL CONFIGURATION STATE ===="
_dump_sdn_state "live" "Final"
log_info "==== END FINAL CONFIGURATION STATE ===="

# Install helper command for DHCP CT deployment.
log_info "Installing msldhcp command to /usr/local/bin..."
if [[ ! -f "$SCRIPT_ROOT/msldhcp" ]]; then
    log_error "msldhcp script not found at $SCRIPT_ROOT/msldhcp"
    exit 1
fi
cp -f "$SCRIPT_ROOT/msldhcp" /usr/local/bin/msldhcp
chmod 0755 /usr/local/bin/msldhcp
log_info "Installed /usr/local/bin/msldhcp"
echo "========================================"
echo "If you need DHCP on a tenant's isolated network, you can add it later:"
echo "  Ex.) ./msldhcp"
echo ""
echo "(It will prompt you to select the tenant VNet and VMID.)"

# Prompt user for router configuration (manual steps)
echo ""
echo "${MSG_MANUAL_STEPS}: ${MSG_ROUTER_CONFIG_TITLE}"
prompt_router_setup

log_info "==== SETUP COMPLETED SUCCESSFULLY ===="
