#!/bin/bash
################################################################################
# Zelogx™ Multi-Project Secure Lab Setup
#
# © 2025 Zelogx. Zelogx™ and the Zelogx logo are trademarks
# of the Zelogx Project. All other marks are property of their respective owners.
#
# Filename: lib/env_generator.sh
# Purpose: Generate .env file from collected configuration
#
# Dependencies:
#   - lib/common.sh
#
# Usage:
#   source "${PROJECT_ROOT}/lib/env_generator.sh"
#
# Notes:
#   - Reads from CONFIG associative array
#   - Reads from global VPN pool variables (OVPN_POOL*, WG_POOL*)
#   - Generates complete .env file with all network configuration
################################################################################

# Direct execution guard (library usage only, English usage per spec v2.0)
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    cat <<'USAGE'
Usage: env_generator.sh (library)
  This file is a library; source it after populating CONFIG associative array.
Notes:
  - Not intended for direct execution
  - Generates .env when called via generate_env()
USAGE
    exit 1
fi

################################################################################
# Function: generate_env
# Description: Generate .env file with all configuration variables
#
# Returns:
#   0: Success
#   1: Error
################################################################################
generate_env() {
    local env_file="${PROJECT_ROOT}/.env"
    local timestamp=$(date +"%Y-%m-%d %H:%M:%S")
    
    log_info "Generating .env file..."
    
    # Create .env file with header
    cat > "$env_file" <<EOF
################################################################################
# Zelogx™ Multi-Project Secure Lab Setup - Environment Configuration
#
# Generated: ${timestamp}
# This file contains all network configuration for the MSL setup
#
# DO NOT EDIT THIS FILE MANUALLY
# Re-run 00_check_env.sh to regenerate with new values
################################################################################

# MainLAN Configuration (auto-detected from vmbr0)
ML_CIDR=${CONFIG[ML_CIDR]}
ML_GW=${CONFIG[ML_GW]}
ML_GW_LO=$(extract_last_octet "${CONFIG[ML_GW]}")

# Proxmox VE Configuration
PVE_IP=${CONFIG[PVE_IP]}
PVE_IP_LO=$(extract_last_octet "${CONFIG[PVE_IP]}")

# Pritunl VM IP Configuration
PT_IG_IP=${CONFIG[PT_IG_IP]}
PT_IG_IP_LO=$(extract_last_octet "${CONFIG[PT_IG_IP]}")
PT_EG_IP=${CONFIG[PT_EG_IP]}
PT_EG_IP_LO=$(extract_last_octet "${CONFIG[PT_EG_IP]}")

# VPN DMZ Network (Pritunl Gateway Network)
VPNDMZ_CIDR=${CONFIG[VPNDMZ_CIDR]}
VPNDMZ_GW=${CONFIG[VPNDMZ_GW]}
VPNDMZ_GW_LO=$(extract_last_octet "${CONFIG[VPNDMZ_GW]}")

# Project Configuration
NUM_PJ=${CONFIG[NUM_PJ]}

# VPN Client Pool Configuration
VPN_POOL=${CONFIG[VPN_POOL]}

# OpenVPN Pool (First half of VPN_POOL)
OVPN_POOL=${OVPN_POOL}

# WireGuard Pool (Second half of VPN_POOL)
WG_POOL=${WG_POOL}

EOF

    # Add per-project OpenVPN pools
    echo "# Per-Project OpenVPN Pools" >> "$env_file"
    for ((i=1; i<=${CONFIG[NUM_PJ]}; i++)); do
        local pj_num=$(printf "%d" "$i")
        local var_name="OVPN_POOL${pj_num}"
        echo "${var_name}=${!var_name}" >> "$env_file"
    done
    echo "" >> "$env_file"
    
    # Add per-project WireGuard pools
    echo "# Per-Project WireGuard Pools" >> "$env_file"
    for ((i=1; i<=${CONFIG[NUM_PJ]}; i++)); do
        local pj_num=$(printf "%d" "$i")
        local var_name="WG_POOL${pj_num}"
        echo "${var_name}=${!var_name}" >> "$env_file"
    done
    echo "" >> "$env_file"
    
    # Add project networks section
    cat >> "$env_file" <<EOF
# Project Networks (All Projects Combined)
PJALL_CIDR=${CONFIG[PJALL_CIDR]}

EOF

    # Add per-project network configurations
    echo "# Per-Project Network Configurations" >> "$env_file"
    for ((i=1; i<=${CONFIG[NUM_PJ]}; i++)); do
        local pj_num=$(printf "%02d" "$i")
        local cidr_key="PJ${pj_num}_CIDR"
        local gw_key="PJ${pj_num}_GW"
        
        echo "PJ${pj_num}_CIDR=${CONFIG[$cidr_key]}" >> "$env_file"
        echo "PJ${pj_num}_GW=${CONFIG[$gw_key]}" >> "$env_file"
        echo "PJ${pj_num}_GW_LO=$(extract_last_octet "${CONFIG[$gw_key]}")" >> "$env_file"
    done
    echo "" >> "$env_file"
    
    # Add port forwarding configuration
    cat >> "$env_file" <<EOF
# Port Forwarding Configuration
# OpenVPN Ports (UDP)
PF_ST_OV=${CONFIG[PF_ST_OV]}
PF_ED_OV=${CONFIG[PF_ED_OV]}

# WireGuard Ports (UDP)
PF_ST_WG=${CONFIG[PF_ST_WG]}
PF_ED_WG=${CONFIG[PF_ED_WG]}

# DNS Configuration
DNS_IP1=${CONFIG[DNS_IP1]}
EOF

    # Add DNS_IP2 only if configured
    if [[ -n "${CONFIG[DNS_IP2]:-}" ]]; then
        echo "DNS_IP2=${CONFIG[DNS_IP2]}" >> "$env_file"
    else
        echo "# DNS_IP2 not configured" >> "$env_file"
    fi
    
    echo "" >> "$env_file"
    echo "################################################################################" >> "$env_file"
    echo "# End of configuration" >> "$env_file"
    echo "################################################################################" >> "$env_file"
    
    log_info ".env file generated successfully: ${env_file}"
    
    # Display summary
    local total_vars=$(grep -c "^[A-Z]" "$env_file" || echo "0")
    echo ""
    if [[ "${MSL_LANG:-en}" == "en" ]]; then
        echo "Summary:"
        echo "  - File: ${env_file}"
        echo "  - Total variables: ${total_vars}"
        echo "  - Projects: ${CONFIG[NUM_PJ]}"
    else
        echo "生成サマリ："
        echo "  - ファイル: ${env_file}"
        echo "  - 変数総数: ${total_vars}"
        echo "  - プロジェクト数: ${CONFIG[NUM_PJ]}"
    fi
    echo ""
    
    return 0
}
