#!/bin/bash
################################################################################
# Zelogx™ Multi-Project Secure Lab Setup
#
# © 2025 Zelogx. Zelogx™ and the Zelogx logo are trademarks
# of the Zelogx Project. All other marks are property of their respective owners.
#
# Filename: lib/svg_generator.sh
# Purpose: Generate network diagram SVG from template with .env values
#
# Main functions/commands used:
#   - generate_svg_diagram: Replace placeholders in SVG template
#   - sed: Text substitution
#
# Dependencies:
#   - lib/common.sh (logging functions)
#   - .env file (generated by env_generator.sh)
#
# Usage:
#   source lib/svg_generator.sh
#   generate_svg_diagram
#
# Notes:
#   - Template files: docs/assets/zelogx-MSL-Setup-template-{2,4,8,16}.svg
#   - Template selection based on NUM_PJ value from .env
#   - Output file: docs/generated/network-diagram.svg
#   - Requires .env file to be generated first
################################################################################

# Direct execution guard (library usage only, English usage per spec v2.0)
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    cat <<'USAGE'
Usage: svg_generator.sh (library)
  This file is a library; source it then call generate_svg_diagram.
Notes:
  - Requires existing .env file
  - Adds SVG to Proxmox notes if user confirms
USAGE
    exit 1
fi

################################################################################
# Function: generate_svg_diagram
# Description: Generate network diagram SVG by replacing template placeholders
#              with actual configuration values from .env file
#
# Main commands/functions used:
#   - sed: Replace ${VARIABLE} placeholders with actual values
#   - cat: Read template file
################################################################################
generate_svg_diagram() {
    local output_dir="${PROJECT_ROOT}/docs/generated"
    local output_file="${output_dir}/network-diagram.svg"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    local env_file="${PROJECT_ROOT}/.env"

    # Check .env exists
    if [[ ! -f "${env_file}" ]]; then
        echo "[ERROR] .env file not found: ${env_file}" >&2
        return 1
    fi

    # Source .env to get NUM_PJ
    source "${env_file}"

    # Select template based on NUM_PJ
    local template_file="${PROJECT_ROOT}/docs/assets/zelogx-MSL-Setup-template-${NUM_PJ}.svg"

    # Check template exists
    if [[ ! -f "${template_file}" ]]; then
        echo "[ERROR] SVG template not found: ${template_file}" >&2
        echo "[ERROR] NUM_PJ=${NUM_PJ} - Valid values are: 2, 4, 8, 16" >&2
        return 1
    fi

    # Create output directory
    mkdir -p "${output_dir}"

    log_info "Generating SVG network diagram..."
    log_info "NUM_PJ: ${NUM_PJ}"
    log_info "Template: ${template_file}"
    log_info "Output: ${output_file}"

    # Build sed script by reading .env file
    local sed_script=""
    
    # Read all variables from .env and create substitutions
    while IFS='=' read -r key value; do
        # Skip comments and empty lines
        [[ "${key}" =~ ^[[:space:]]*# ]] && continue
        [[ -z "${key}" ]] && continue
        
        # Remove quotes from value if present
        value="${value%\"}"
        value="${value#\"}"
        
        # Add substitution
        sed_script+="s|\\\${${key}}|${value}|g;"
    done < "${env_file}"

    # Apply substitutions
    if sed "${sed_script}" "${template_file}" > "${output_file}"; then
        log_info "SVG diagram generated successfully"
        log_info "File: ${output_file}"
        
        # Update Proxmox node notes with diagram URL
        update_pve_notes "${output_file}"
        
        # Log summary
        log_info "SVG generation summary:"
        log_info "  - File: ${output_file}"
        log_info "  - Template: ${template_file}"
        log_info "  - Generated: ${timestamp}"
        
        return 0
    else
        echo "[ERROR] Failed to generate SVG diagram" >&2
        return 1
    fi
}

################################################################################
# Function: update_pve_notes
# Description: Update Proxmox node notes with network diagram image
#
# Main commands/functions used:
#   - pvesh: Proxmox API client
#   - cp: Copy SVG to web-accessible location
#   - hostname: Get node name
################################################################################
update_pve_notes() {
    local svg_file="$1"
    local node_name=$(hostname)
    local svg_web_name="msl-setup-network-diagram.svg"
    local svg_web_path="/usr/share/pve-manager/images/${svg_web_name}"
    
    echo ""
    echo "================================================================"
    echo "${MSG_SVG_NOTE_TITLE}"
    echo "================================================================"
    echo ""
    echo "${MSG_SVG_NOTE_QUESTION}"
    echo ""
    echo "${MSG_SVG_NOTE_DETAILS}"
    printf "${MSG_SVG_NOTE_COPY}\n" "${svg_web_path}"
    printf "${MSG_SVG_NOTE_APPEND}\n" "${svg_web_name}"
    echo "${MSG_SVG_NOTE_PRESERVE}"
    echo ""
    printf "${MSG_SVG_NOTE_LOCATION}\n" "${node_name}"
    echo ""
    
    # Ask user confirmation
    local response
    read -p "${MSG_SVG_NOTE_CONFIRM}[Y/n]: " response
    
    if [[ "$response" =~ ^[nN]$ ]]; then
        log_info "Skipped adding network diagram to notes"
        return 0
    fi
    
    echo ""
    log_info "Copying SVG to web-accessible location..."
    
    # Copy SVG to Proxmox web directory
    if ! cp "${svg_file}" "${svg_web_path}"; then
        echo "[ERROR] Failed to copy SVG file to ${svg_web_path}" >&2
        echo "[ERROR] Please check permissions (may need root access)" >&2
        return 1
    fi
    
    chmod 644 "${svg_web_path}"
    log_info "SVG copied successfully"
    
    log_info "Updating node notes..."
    
    # Get existing notes from JSON output
    local existing_notes=""
    local json_output
    json_output=$(pvesh get "/nodes/${node_name}/config" --output-format json 2>/dev/null || echo '{}')
    
    # Extract description field, handling escaped characters
    if command -v python3 &>/dev/null; then
        existing_notes=$(echo "$json_output" | python3 -c "import sys,json; data=json.load(sys.stdin); print(data.get('description', '').rstrip())" 2>/dev/null || true)
    else
        # Fallback: use grep with proper escaping
        existing_notes=$(echo "$json_output" | grep -oP '"description"\s*:\s*"\K[^"]*' | sed 's/\\n/\n/g' | sed 's/\\"/"/g' || true)
    fi
    
    # Create new notes content (append to existing)
    local new_content="
---
MSL Setup - Network Diagram

<img src=\"/pve2/images/${svg_web_name}\">"

    # If an existing MSL Setup diagram block is present, remove it and overwrite
    local full_notes
    if echo "${existing_notes}" | grep -q "msl-setup-network-diagram.svg" || echo "${existing_notes}" | grep -q "MSL Setup - Network Diagram"; then
        log_info "Network diagram already present in notes (overwriting existing entry)"
        # Remove previous MSL Setup block (everything from the marker onwards)
        local cleaned_notes
        cleaned_notes=$(echo "${existing_notes}" | awk '/^MSL Setup - Network Diagram/{exit} {print}')
        # Remove trailing separator line if present to avoid duplicate '---' markers
        cleaned_notes=$(echo "${cleaned_notes}" | awk 'BEGIN{ln=0} {lines[ln++]=$0} END{ if(ln>0 && lines[ln-1]=="---") ln--; for(i=0;i<ln;i++) print lines[i] }')
        full_notes="${cleaned_notes}${new_content}"
    else
        full_notes="${existing_notes}${new_content}"
    fi

    # Update node notes via API (overwrite or append)
    if pvesh set "/nodes/${node_name}/config" --description "${full_notes}" 2>/dev/null; then
        log_info "Node notes updated successfully"
        echo ""
        echo "================================================================"
        msg_printf SVG_NOTICE
        echo "================================================================"
        echo ""
        msg_printf SVG_URL_LABEL
        echo "  https://$(hostname -I | awk '{print $1}'):8006/#v1:0:=node%2F${node_name}:4:=notes::::::"
        echo ""
        msg_printf SVG_GUI_LABEL
        echo "  Datacenter > ${node_name} > Summary > Notes"
        echo ""
        return 0
    else
        echo "[WARN] $(date '+%Y-%m-%d %H:%M:%S') Failed to update node notes (API error or permission issue)"
        return 1
    fi
}

